/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.enter;

import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Vector;
import session.GamerClient;

/**
 *
 * @author Olga
 */
public class WaitForPlayersView extends javax.swing.JPanel {
    
    private GamerClient clientHandler;
    
    private boolean buttonWithSpinner;
    private Timer dummyTimer;
    private static final String WAITTEXT = "Waiting for other users";
    
    private static int tick = 0;

    /**
     * Creates new form WaitForPlayersView
     */
    public WaitForPlayersView(GamerClient handler) {
        this.clientHandler = handler;
        initComponents();
    }
    
    public void showWaitForOthersOnButton() {
        
        if(buttonWithSpinner == false) {
            
            buttonWithSpinner = true;
            dummyTimer = new Timer();
            dummyTimer.schedule(new TimerTask() {

                    public void run() {
                        
                    String buttonText = WAITTEXT;

                    for(int i = 0; i < tick; i++) {
                        buttonText = buttonText + ".";
                    }
                    
                    tick++;

                    if(tick > 7) {
                        tick = 0;
                    }

                    startGameButton.setText(buttonText);
                }
            }, 0, 1000);
        }
    }
    
    public void updateListView(ArrayList<String> namesList) {
        this.playersList.setListData(new Vector(namesList));
    }
    
    public void changeStartButtonState(boolean buttonEnabled) {
        if(!buttonWithSpinner) {
            this.startGameButton.setEnabled(buttonEnabled);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commentLabel = new javax.swing.JLabel();
        otherPlayersLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playersList = new javax.swing.JList();
        startGameButton = new javax.swing.JButton();

        commentLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        commentLabel.setText("Setting up new game....");

        otherPlayersLabel.setText("Other players in this game so far: ");

        jScrollPane1.setViewportView(playersList);

        startGameButton.setText("Start game");
        startGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startGamePressed(evt);
            }
        });
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentLabel)
                            .addComponent(otherPlayersLabel))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(startGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherPlayersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void startGamePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startGamePressed
        this.clientHandler.startGame();
    }//GEN-LAST:event_startGamePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commentLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel otherPlayersLabel;
    private javax.swing.JList playersList;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables
}
